### ISSUE TITLE
App needs update 

### ISSUE THREAD

**Issue by mberndtsson** [steffjenl/com.ubnt.unifiprotect#13]
After the update of Cloud Key the port 7443 dosent work any more

**Comment by steffjenl** [comment]
Please select UnifiOS option and poort 443

**Comment by mberndtsson** [comment]
HiHow do I select UnifiOS option in the app?
    	
    	Med vänliga hälsningarMagnus BerndtssonMobil: +46 70 239 29 91
    
  
 Från: steffjenl <notifications@github.com>Skickat: fredag, januari 22, 2021 10:55 fmTill: steffjenl/com.ubnt.unifiprotectKopia: mberndtsson; AuthorÄmne: Re: [steffjenl/com.ubnt.unifiprotect] App needs update (#13) 
Please select UnifiOS option and poort 443

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/steffjenl/com.ubnt.unifiprotect/issues/13#issuecomment-765286029",
"url": "https://github.com/steffjenl/com.ubnt.unifiprotect/issues/13#issuecomment-765286029",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by steffjenl** [comment]
Hello,

In the app settings please select ‘UnifiOS (o.a. Dream machine Pro).

[cid:image001.png@01D6F0B2.D5B2FB50]

Met vriendelijke groet,
 Stèphan Eizinga

[monkeysoft_logo]

Eiland van Surya 23
1705 SH Heerhugowaard

Telefoon: 072-7437296
Mobiel: 06-83237940
E-mail: stephan@monkeysoft.nl<mailto:stephan@monkeysoft.nl>
Website: monkeysoft.nl<https://monkeysoft.nl/>

Van: mberndtsson <notifications@github.com>
Verzonden: vrijdag 22 januari 2021 11:35
Aan: steffjenl/com.ubnt.unifiprotect <com.ubnt.unifiprotect@noreply.github.com>
CC: Stèphan Eizinga <stephan@monkeysoft.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [steffjenl/com.ubnt.unifiprotect] App needs update (#13)







HiHow do I select UnifiOS option in the app?

Med vänliga hälsningarMagnus BerndtssonMobil: +46 70 239 29 91


 Från: steffjenl <notifications@github.com<mailto:notifications@github.com>>Skickat: fredag, januari 22, 2021 10:55 fmTill: steffjenl/com.ubnt.unifiprotectKopia: mberndtsson; AuthorÄmne: Re: [steffjenl/com.ubnt.unifiprotect] App needs update (#13)
Please select UnifiOS option and poort 443

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/steffjenl/com.ubnt.unifiprotect/issues/13#issuecomment-765286029",
"url": "https://github.com/steffjenl/com.ubnt.unifiprotect/issues/13#issuecomment-765286029",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by steffjenl** [comment]
Hello, can you find the option in the app settings page?
