### ISSUE TITLE
Starting/restarting the app fires a motion event

### ISSUE THREAD

**Issue by denniedegroot** [steffjenl/com.ubnt.unifiprotect#4]
Everytime I start/restart the app a 'motion alarm' is fired.I would expect it to fire only when motion is detected not when the app is started/restarted.

**Comment by steffjenl** [comment]
I've heard this from another user before. But I store the last move in a capability value from Homey itself. It seems that in some situations this value is empty and then everything has to be refilled again.

I suspect that this will not happen if you remove the app from the store instead of side-loading the app.

**Comment by denniedegroot** [comment]
I just installed the test version and restarted it a couple of times and also reboot Homey. I didn't get a notification anymore so I think it's solved somewhere. I am closing this issue. Thanks!
